### ISSUE TITLE
Could not read 'meta.json'

### ISSUE THREAD

**Issue by MaellyPooh** [Al-Azif/ps4-payload-guest#7]
Payload Guest refuses to load the meta.json file located in "/data/payloads/meta.json". The file follows the correct format, and has 777 attribute. Deleting the file and refreshing shows all available payloads as expected.

**Comment by Al-Azif** [comment]
Can you post the `.json` so I can see if I can reproduce the issue?

**Comment by ismalopese** [comment]
Not the original because I change some payloads, but same structure. 

[meta.json](https://github.com/user-attachments/files/17685890/meta.json

**Comment by Al-Azif** [comment]
The JSON is invalid, you have trailing commas on the `icon:` line.

**Comment by MaellyPooh** [comment]
I feel so dumb now 😅. Guess I didn't check before copy/pasting the whole thing. Thanks for the fixed version.
 
 I hope you are doing well, mate. Cheers.

**Comment by Al-Azif** [comment]
No problem, happy new year.
